# Generated by Django 4.1.7 on 2023-03-31 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('serial', models.CharField(max_length=150)),
                ('num_ports', models.IntegerField()),
                ('mac_address', models.CharField(max_length=25)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('serial', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('firmware', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('hostname', models.CharField(max_length=50)),
                ('ip_static', models.BooleanField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('serial', models.CharField(max_length=150)),
                ('frequency', models.CharField(max_length=10)),
                ('voltage', models.CharField(max_length=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QRScanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('serial', models.CharField(max_length=150)),
                ('port_type', models.CharField(max_length=10)),
                ('resolution', models.CharField(max_length=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LCB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('serial', models.CharField(max_length=150)),
                ('voltage', models.CharField(max_length=25)),
                ('connector', models.CharField(max_length=25)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DVR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('serial', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('firmware', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('storage_capacity', models.CharField(max_length=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('serial', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('firmware', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('frame_rate', models.CharField(max_length=25)),
                ('compression_format', models.CharField(max_length=10)),
                ('motion_detection', models.BooleanField()),
                ('location', models.CharField(max_length=100)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
