# Generated by Django 4.1.7 on 2023-03-31 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_switch_router_rfid_qrscanner_lcb_dvr_camera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='asset',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='dvr',
            old_name='asset',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='lcb',
            old_name='asset',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='lcd',
            old_name='asset',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='qrscanner',
            old_name='asset',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='rfid',
            old_name='asset',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='router',
            old_name='asset',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='asset',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='camera',
            name='encrypted_password',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dvr',
            name='encrypted_password',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='encrypted_password',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('serial', models.CharField(max_length=150)),
                ('cpu', models.CharField(max_length=50)),
                ('android_version', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
