# Generated by Django 4.1.7 on 2023-03-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_rename_asset_camera_parent_rename_asset_dvr_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='encrypted_password',
        ),
        migrations.RemoveField(
            model_name='dvr',
            name='encrypted_password',
        ),
        migrations.RemoveField(
            model_name='router',
            name='encrypted_password',
        ),
        migrations.AddField(
            model_name='camera',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dvr',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
