# Generated by Django 4.1.7 on 2023-04-04 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_maintenance_distrispot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='parent',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='dvr',
            old_name='parent',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='ipc',
            old_name='parent',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='lcb',
            old_name='parent',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='lcd',
            old_name='parent',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='qrscanner',
            old_name='parent',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='rfid',
            old_name='parent',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='router',
            old_name='parent',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='switch',
            old_name='parent',
            new_name='asset',
        ),
    ]
