# Generated by Django 4.1.7 on 2023-04-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_rename_parent_camera_asset_rename_parent_dvr_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='resolution',
            field=models.CharField(default='720p', max_length=25),
            preserve_default=False,
        ),
    ]
