# Generated by Django 4.1.7 on 2023-04-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_powersupply'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
