# Generated by Django 4.1.7 on 2023-04-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_type_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dvr',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ipc',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lcb',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lcd',
            name='name',
        ),
        migrations.RemoveField(
            model_name='powersupply',
            name='name',
        ),
        migrations.RemoveField(
            model_name='qrscanner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rfid',
            name='name',
        ),
        migrations.RemoveField(
            model_name='router',
            name='name',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='name',
        ),
    ]
