# Generated by Django 4.1.7 on 2023-04-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_rename_location_customer_location_remove_camera_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='location',
        ),
    ]
