# Generated by Django 4.1.7 on 2023-04-13 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_remove_camera_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distrispot',
            name='parent',
        ),
        migrations.AddField(
            model_name='distrispot',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distrispot', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='dvr',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dvr', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='ipc',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipc', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='lcb',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcb', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='lcd',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcd', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psu', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='qrscanner',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qrscanner', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='rfid',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfid', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='router',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='router', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switch', to='assets.asset'),
        ),
    ]
