# Generated by Django 4.1.7 on 2023-04-20 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_customer_email_customer_phone_alter_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrispotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.RemoveField(
            model_name='distrispot',
            name='location',
        ),
        migrations.RemoveField(
            model_name='distrispot',
            name='name',
        ),
        migrations.AddField(
            model_name='distrispot',
            name='slots_num',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distrispot',
            name='type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='assets.distrispottype'),
            preserve_default=False,
        ),
    ]
