# Generated by Django 4.1.7 on 2023-04-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_remove_asset_location_remove_customer_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipc',
            name='display_adapter',
            field=models.CharField(default='HDMI', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipc',
            name='memory',
            field=models.CharField(default='4 GB DDR4', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipc',
            name='power_intake',
            field=models.CharField(default='DC Jack', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ipc',
            name='storage',
            field=models.CharField(default='64 GB mSATA SSD', max_length=50),
            preserve_default=False,
        ),
    ]
