# Generated by Django 4.1.7 on 2023-04-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_ipc_input_voltage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='ip_address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='dvr',
            name='ip_address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='router',
            name='ip_address',
            field=models.CharField(max_length=150),
        ),
    ]
