# Generated by Django 4.1.7 on 2023-04-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_alter_distrispot_type_delete_distrispottype'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrispot',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=20),
        ),
    ]
