# Generated by Django 4.1.7 on 2023-05-04 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_distrispot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distrispot',
            name='maintenance',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='distrispot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.distrispot'),
        ),
    ]
