# Generated by Django 4.1.7 on 2023-05-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
